---
title: "scATAC-seq Rat Metrial Glands"
author: "Ha T. H. Vu"
output: html_document
---
  
```{r setup, include=FALSE}
options(max.print = "75")
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>",
  fig.path = "Files/",
  fig.width = 15,
  prompt = FALSE,
  tidy = FALSE,
  message = FALSE,
  warning = TRUE
)
knitr::opts_knit$set(width = 75)
```

This is a documentation for analyses of scATAC-seq data, generated from rat metrial gland tissues on gestational day (GD) 15.5 and 19.5. <br>

```{r}
library("org.Rn.eg.db")
library("clusterProfiler")

go <- function(genes) {
  GO <- enrichGO(gene = genes, OrgDb=org.Rn.eg.db, ont = "BP", pvalueCutoff = 0.05, qvalueCutoff = 0.05, maxGSSize=500, readable = T, keyType = "ENSEMBL")
  goSimplify <- simplify(GO)
  res <- as.data.frame(goSimplify)
  #res$Rank <- seq(1, nrow(res))
  res$GeneRatio <- sapply(strsplit(res$GeneRatio, "/"), function(x) as.numeric(x[1])/as.numeric(x[2]))
  res$BgRatio <- sapply(strsplit(res$BgRatio, "/"), function(x) as.numeric(x[1])/as.numeric(x[2]))
  res$Fold <- as.numeric(res$GeneRatio)/as.numeric(res$BgRatio)
  res <- res[res$qvalue <= 0.05 & res$Fold >= 2 & res$Count >= 5,]
  
  return(res)
}
```

```{r}
library(TissueEnrich)
library(ggplot2)

load(file = "Files/combine-test-expression1.Rdata")

ratHumanOrthologs<-dataset$GRCH38$ratHumanOrthologs
humanGeneMapping<-dataset$GRCH38$humanGeneMapping

#For VentoTormo Data
d <- dataset$PlacentaDeciduaBloodData
data <- d$expressionData
cellDetails <- d$cellDetails

expressionData <- data[intersect(row.names(data), ratHumanOrthologs$Human.gene.stable.ID),]
se <- SummarizedExperiment(assays = SimpleList(as.matrix(expressionData)), rowData = row.names(expressionData), colData = colnames(expressionData))
cellSpecificGenesExp <- teGeneRetrieval(se, expressedGeneThreshold = 1)
```

```{r}
runPCE <- function(inputGenes, nameType = c("Gene.name", "Gene.stable.ID")) {
  if (nameType == "Gene.name") {
    humanOrthologs <- ratHumanOrthologs[ratHumanOrthologs$Gene.name %in% toupper(inputGenes),]
  } else {
    humanOrthologs <- ratHumanOrthologs[ratHumanOrthologs$Gene.stable.ID %in% inputGenes,]
  }
  inputGenes <- humanOrthologs$Human.gene.stable.ID
  print(paste("Number of input genes found is", length(inputGenes)))
  gs <- GeneSet(geneIds=toupper(inputGenes))
  output2 <- teEnrichmentCustom(gs, cellSpecificGenesExp)
  enrichmentOutput <- setNames(data.frame(assay(output2[[1]]), row.names = rowData(output2[[1]])[,1]), colData(output2[[1]])[,1])
  row.names(cellDetails) <- cellDetails$RName
  enrichmentOutput$Tissue <- cellDetails[row.names(enrichmentOutput), "CellName"]
  
  return(enrichmentOutput)
}

plotPCE <- function(enrichmentOutput, name) {
  p <- ggplot(enrichmentOutput,aes(x=reorder(Tissue,-Log10PValue),y=Log10PValue,
                                 label = Tissue.Specific.Genes, fill=Tissue))+
  geom_bar(stat = 'identity')+
    labs(x='', y = '-LOG10(Adj. P-Value)')+
    theme_bw()+
    theme(legend.position='none', plot.margin=unit(c(1,1,1,1),"cm"))+
    theme(plot.title = element_text(hjust = 0.5,size = 20),axis.title =
            element_text(size=15))+
    theme(axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1),
          panel.grid.major= element_blank(),panel.grid.minor = element_blank())+
    ggtitle(name)
  
  return(p)
}
```

TissueEnrich
```{r}
runTE <- function(inputGenes, nameType = c("Gene.name", "Gene.stable.ID")) {
  if (nameType == "Gene.name") {
    humanOrthologs <- ratHumanOrthologs[ratHumanOrthologs$Gene.name %in% toupper(inputGenes),]
  } else {
    humanOrthologs <- ratHumanOrthologs[ratHumanOrthologs$Gene.stable.ID %in% inputGenes,]
  }
  inputGenes <- humanOrthologs$Human.gene.name
  print(paste("Number of input genes found is", length(inputGenes)))
  gs <- GeneSet(geneIds=toupper(inputGenes),organism="Homo Sapiens",geneIdType=SymbolIdentifier())
  output <- teEnrichment(gs)
  enrichmentOutput <- setNames(data.frame(assay(output[[1]]), row.names = rowData(output[[1]])[,1]), colData(output[[1]])[,1])
  enrichmentOutput$Tissue <- rownames(enrichmentOutput)
  
  return(enrichmentOutput)
}
```

## GD 15.5:
```{r}
library(Signac)
library(Seurat)
library(ggplot2)
library(GenomicRanges)
library(patchwork)
set.seed(1234)

closest_genes <- read.table("/work/LAS/geetu-lab/hhvu/project3_scATAC/scATAC-seq-analysis/4_RNAintegration/2_MACS2Peaks/annotation_scRNAseq/gd15.5-tbc-toGenes.txt", sep = "\t")
t <- table(closest_genes$gene_name)

load("/work/LAS/geetu-lab/hhvu/project3_scATAC/scATAC-seq-analysis/4_RNAintegration/scRNA-seqFiles/gd15.5_res0.8.rda")
data

exp <- AverageExpression(data)
exp <- as.data.frame(exp$RNA)
```

```{r}
genes <- names(t[t >= 3])

exp <- exp[order(rownames(exp)),]
exp$gene <- rownames(exp)
df <- exp[exp$gene %in% names(t), c("gene", "23")]
colnames(df) <- c("gene", "value")
df$category <- ifelse(df$gene %in% genes, ">= 3 peaks", "< 3 peaks")

wilcox.test(df[df$category == ">= 3 peaks", "value"], df[df$category == "< 3 peaks", "value"], alternative = "greater")

ggplot(df, aes(x=category, y=log10(value+10^(-5)))) + geom_violin() + ggtitle("Cutoff = 3")
```

```{r}
t2 <- closest_genes[closest_genes$gene_name %in% df[df$category == ">= 3 peaks", "gene"],]
#go(unique(t2$ensembl_gene_id)) #no terms enriched

gd15.5tbc <- read.table("/work/LAS/geetu-lab/hhvu/project3_scATAC/scRNA-seq-analysis/3_cluster_DEG/rmChrMTgenes/GD15.5/res0.8/gd15.5-wilcoxin-cluster23.txt", header = T)
length(intersect(df[df$category == ">= 3 peaks", "gene"], gd15.5tbc$gene))
length(unique(df[df$category == ">= 3 peaks", "gene"]))
intersect(df[df$category == ">= 3 peaks", "gene"], gd15.5tbc$gene) #57 genes out of 255 genes are TBC genes
genes <- names(t[t >= 4])
length(intersect(genes, gd15.5tbc$gene)) #25 out of 57 genes have >= 4 peaks
genes <- names(t[t >= 5])
length(genes)
length(intersect(genes, gd15.5tbc$gene)) #16 out of 57 genes have >= 5 peaks
```

```{r}
load("/work/LAS/geetu-lab/hhvu/project3_scATAC/rnor6.rda")
load("/work/LAS/geetu-lab/hhvu/project3_scATAC/rnor6.ranges.rda")
load("/work/LAS/geetu-lab/hhvu/project3_scATAC/scATAC-seq-analysis/4_RNAintegration/2_MACS2Peaks/annotation_scRNAseq/gd15.5-ATACwithRNAlables.rda")

Idents(rats) <- rats@meta.data$predicted.id # change from old identities to those predicted by scRNA-seq
DefaultAssay(rats) <- 'MACSpeaks'
Annotation(rats) <- rnor6.ranges

pileup <- AverageExpression(rats, "MACSpeaks")
pileup <- pileup$MACSpeaks
pileup2 <- as.data.frame(pileup[closest_genes$query_region,])
pileup3 <- data.frame(regions=as.character(rownames(pileup2)), TBCregions=as.numeric(pileup2$`Invasive trophoblast cells`))

exp3 <- data.frame(genes=rownames(exp), TBC=exp$`23`)
t1 <- dplyr::left_join(closest_genes[,c("gene_name", "query_region")], exp3, by = c("gene_name" = "genes"))
t1 <- dplyr::left_join(t1, pileup3, by = c("query_region" = "regions"))
t1$TBC <- ifelse(is.na(t1$TBC) == TRUE, 0, t1$TBC)

quantile(t1$TBCregions)
quantile(t1$TBC)
```

Binning open regions and genes:
```{r}
#MA - HE - tissue specific
maHe <- t1[t1$TBCregions < quantile(t1$TBCregions, 0.4) &
           t1$TBC > quantile(t1$TBC, 0.75),]
length(unique(maHe$gene_name))
length(unique(maHe$query_region))

go_maHe <- go(unique(closest_genes[closest_genes$gene_name %in% maHe$gene_name, "ensembl_gene_id"]))
go_maHe

pce_maHE <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_maHE, "PCE MA-HE gd15.5")

te_maHE <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_maHE <- te_maHE[te_maHE$Log10PValue >= -log10(0.05) & te_maHE$fold.change >= 2 & te_maHE$samples >= 5,]
plotPCE(te_maHE, "TE MA-HE gd15.5")
```

```{r}
#HA - HE - house keeping
haHe <- t1[t1$TBCregions > quantile(t1$TBCregions, 0.75) &
             t1$TBC > quantile(t1$TBC, 0.75),]
length(unique(haHe$gene_name))
length(unique(haHe$query_region))

go_haHe <- go(unique(closest_genes[closest_genes$gene_name %in% haHe$gene_name, "ensembl_gene_id"]))
go_haHe

pce_haHE <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_haHE, "PCE HA-HE gd15.5")

te_haHE <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_haHE <- te_haHE[te_haHE$Log10PValue >= -log10(0.05) & te_haHE$fold.change >= 2 & te_haHE$samples >= 5,]
plotPCE(te_haHE, "TE HA-HE gd15.5")
```


```{r}
#MA - ME - sensory perception
maMe <- t1[t1$TBCregions < quantile(t1$TBCregions, 0.4) &
           t1$TBC < quantile(t1$TBC, 0.4),]
length(unique(maMe$gene_name))
length(unique(maMe$query_region))

go_maMe <- go(unique(closest_genes[closest_genes$gene_name %in% maMe$gene_name, "ensembl_gene_id"]))
go_maMe

pce_maMe <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_maMe, "PCE MA - ME gd15.5")

te_maMe <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_maMe <- te_maMe[te_maMe$Log10PValue >= -log10(0.05) & te_maMe$fold.change >= 2 & te_maMe$samples >= 5,]
plotPCE(te_maMe, "TE MA - ME gd15.5")
```

```{r}
#HA - ME - repressed neural
haMe <- t1[t1$TBCregions > quantile(t1$TBCregions, 0.75) &
             t1$TBC < quantile(t1$TBC, 0.4),]
length(unique(haMe$gene_name))
length(unique(haMe$query_region))

go_haMe <- go(unique(closest_genes[closest_genes$gene_name %in% haMe$gene_name, "ensembl_gene_id"]))
go_haMe

pce_haMe <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_haMe, "PCE HA - ME gd15.5")

te_haMe <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_haMe <- te_haMe[te_haMe$Log10PValue >= -log10(0.05) & te_haMe$fold.change >= 2 & te_haMe$samples >= 5,]
plotPCE(te_haMe, "TE HA - ME gd15.5")
```

If we only have two groups, high expression and mid-low expression:
```{r}
#HE
he <- t1[t1$TBC > quantile(t1$TBC, 0.75),]
length(unique(he$gene_name))
length(unique(he$query_region))

go_he <- go(unique(closest_genes[closest_genes$gene_name %in% he$gene_name, "ensembl_gene_id"]))
go_he

pce_he <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% he$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_he, "PCE HE gd15.5")

te_he <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% he$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_he <- te_he[te_he$Log10PValue >= -log10(0.05) & te_he$fold.change >= 2 & te_he$samples >= 5,]
plotPCE(te_he, "TE HE gd15.5")
```

```{r}
#ME
me <- t1[t1$TBC < quantile(t1$TBC, 0.4),]
length(unique(me$gene_name))
length(unique(me$query_region))

go_me <- go(unique(closest_genes[closest_genes$gene_name %in% me$gene_name, "ensembl_gene_id"]))
go_me

pce_me <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% me$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_me, "PCE ME gd15.5")

te_me <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% me$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_me <- te_me[te_me$Log10PValue >= -log10(0.05) & te_me$fold.change >= 2 & te_me$samples >= 5,]
plotPCE(te_me, "TE ME gd15.5")
```



## GD 19.5:
```{r}
set.seed(1234)

closest_genes <- read.table("/work/LAS/geetu-lab/hhvu/project3_scATAC/scATAC-seq-analysis/4_RNAintegration/2_MACS2Peaks/annotation_scRNAseq/gd19.5-tbc-toGenes.txt", sep = "\t")
t <- table(closest_genes$gene_name)

load("/work/LAS/geetu-lab/hhvu/project3_scATAC/scATAC-seq-analysis/4_RNAintegration/scRNA-seqFiles/gd19.5-4-5-6-7_res0.8.rda")
data2

exp <- AverageExpression(data2)
exp <- as.data.frame(exp$RNA)
```

```{r}
genes <- names(t[t >= 3])

exp <- exp[order(rownames(exp)),]
exp$gene <- rownames(exp)
df <- exp[exp$gene %in% names(t), c("gene", "6")]
colnames(df) <- c("gene", "value")
df$category <- ifelse(df$gene %in% genes, ">= 3 peaks", "< 3 peaks")

wilcox.test(df[df$category == ">= 3 peaks", "value"], df[df$category == "< 3 peaks", "value"], alternative = "greater")
ggplot(df, aes(x=category, y=log10(value+10^(-5)))) + geom_violin() + ggtitle("Cutoff = 3")
```
```{r}
t2 <- closest_genes[closest_genes$gene_name %in% df[df$category == ">= 3 peaks", "gene"],]
#go(unique(t2$ensembl_gene_id)) #no terms enriched

gd19.5tbc <- read.table("/work/LAS/geetu-lab/hhvu/project3_scATAC/scRNA-seq-analysis/3_cluster_DEG/rmChrMTgenes/GD19.5/res0.8/gd19.5-wilcoxin-cluster6.txt", header = T)
length(intersect(df[df$category == ">= 3 peaks", "gene"], gd19.5tbc$gene))
intersect(df[df$category == ">= 3 peaks", "gene"], gd19.5tbc$gene) #39 genes out of 100 genes are TBC genes
genes <- names(t[t >= 4])
length(intersect(genes, gd19.5tbc$gene)) #12 out of 39 genes have >= 4 peaks
genes <- names(t[t >= 5])
length(intersect(genes, gd19.5tbc$gene)) #5 out of 39 genes have >= 5 peaks
```

```{r}
load("/work/LAS/geetu-lab/hhvu/project3_scATAC/scATAC-seq-analysis/4_RNAintegration/2_MACS2Peaks/annotation_scRNAseq/gd19.5-ATACwithRNAlables.rda")

Idents(rats) <- rats@meta.data$predicted.id # change from old identities to those predicted by scRNA-seq
DefaultAssay(rats) <- 'MACSpeaks'
Annotation(rats) <- rnor6.ranges

pileup <- AverageExpression(rats, "MACSpeaks")
pileup <- pileup$MACSpeaks
pileup2 <- as.data.frame(pileup[closest_genes$query_region,])
pileup3 <- data.frame(regions=as.character(rownames(pileup2)), TBCregions=as.numeric(pileup2$`Invasive trophoblast cells`))

exp3 <- data.frame(genes=rownames(exp), TBC=exp$`6`)
t1 <- dplyr::left_join(closest_genes[,c("gene_name", "query_region")], exp3, by = c("gene_name" = "genes"))
t1 <- dplyr::left_join(t1, pileup3, by = c("query_region" = "regions"))
t1$TBC <- ifelse(is.na(t1$TBC) == TRUE, 0, t1$TBC)

quantile(t1$TBCregions)
quantile(t1$TBC)
```

Binning open regions and genes:
```{r}
#MA - HE - tissue specific
maHe <- t1[t1$TBCregions < quantile(t1$TBCregions, 0.4) &
             t1$TBC > quantile(t1$TBC, 0.75),]
length(unique(maHe$gene_name))
length(unique(maHe$query_region))

go_maHe <- go(unique(closest_genes[closest_genes$gene_name %in% maHe$gene_name, "ensembl_gene_id"]))
go_haHe

pce_maHE <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_maHE, "PCE MA-HE gd19.5")
pce_maHE <- pce_maHE[pce_maHE$Log10PValue >= -log10(0.05) & pce_maHE$fold.change >= 2 & pce_maHE$Tissue.Specific.Genes >= 5,]

te_maHE <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_maHE <- te_maHE[te_maHE$Log10PValue >= -log10(0.05) & te_maHE$fold.change >= 2 & te_maHE$samples >= 5,]
plotPCE(te_maHE, "TE MA-HE gd19.5")
```

```{r}
#HA - HE - house keeping
haHe <- t1[t1$TBCregions > quantile(t1$TBCregions, 0.75) &
             t1$TBC > quantile(t1$TBC, 0.75),]
length(unique(haHe$gene_name))
length(unique(haHe$query_region))

go_haHe <- go(unique(closest_genes[closest_genes$gene_name %in% haHe$gene_name, "ensembl_gene_id"]))
go_haHe

pce_haHE <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_haHE, "PCE HA-HE gd19.5")
pce_haHE <- pce_haHE[pce_haHE$Log10PValue >= -log10(0.05) & pce_haHE$fold.change >= 2 & pce_haHE$Tissue.Specific.Genes >= 5,]

te_haHE <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haHe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_haHE <- te_haHE[te_haHE$Log10PValue >= -log10(0.05) & te_haHE$fold.change >= 2 & te_haHE$samples >= 5,]
plotPCE(te_haHE, "TE HA-HE gd19.5")
```


```{r}
#MA - ME - sensory perception
maMe <- t1[t1$TBCregions < quantile(t1$TBCregions, 0.4) &
             t1$TBC < quantile(t1$TBC, 0.4),]
length(unique(maMe$gene_name))
length(unique(maMe$query_region))

go_maMe <- go(unique(closest_genes[closest_genes$gene_name %in% maMe$gene_name, "ensembl_gene_id"]))
go_maMe

pce_maMe <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_maMe, "PCE MA - ME gd19.5")

te_maMe <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% maMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_maMe <- te_maMe[te_maMe$Log10PValue >= -log10(0.05) & te_maMe$fold.change >= 2 & te_maMe$samples >= 5,]
plotPCE(te_maMe, "TE MA - ME gd19.5")
```

```{r}
#HA - ME - repressed neural
haMe <- t1[t1$TBCregions > quantile(t1$TBCregions, 0.75) &
             t1$TBC < quantile(t1$TBC, 0.4),]
length(unique(haMe$gene_name))
length(unique(haMe$query_region))

go_haMe <- go(unique(closest_genes[closest_genes$gene_name %in% haMe$gene_name, "ensembl_gene_id"]))
go_haMe

pce_haMe <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_haMe, "PCE HA - ME gd19.5")

te_haMe <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% haMe$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_haMe <- te_haMe[te_haMe$Log10PValue >= -log10(0.05) & te_haMe$fold.change >= 2 & te_haMe$samples >= 5,]
plotPCE(te_haMe, "TE HA - ME gd19.5")
```
If we only have two groups, high expression and mid-low expression:
```{r}
#HE
he <- t1[t1$TBC > quantile(t1$TBC, 0.75),]
length(unique(he$gene_name))
length(unique(he$query_region))

go_he <- go(unique(closest_genes[closest_genes$gene_name %in% he$gene_name, "ensembl_gene_id"]))
go_he

pce_he <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% he$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_he, "PCE HE gd19.5")

te_he <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% he$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_he <- te_he[te_he$Log10PValue >= -log10(0.05) & te_he$fold.change >= 2 & te_he$samples >= 5,]
plotPCE(te_he, "TE HE gd19.5")
```

```{r}
#ME
me <- t1[t1$TBC < quantile(t1$TBC, 0.4),]
length(unique(me$gene_name))
length(unique(me$query_region))

go_me <- go(unique(closest_genes[closest_genes$gene_name %in% me$gene_name, "ensembl_gene_id"]))
go_me

pce_me <- runPCE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% me$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
plotPCE(pce_me, "PCE ME gd19.5")

te_me <- runTE(inputGenes = unique(closest_genes[closest_genes$gene_name %in% me$gene_name, "ensembl_gene_id"]), nameType = "Gene.stable.ID")
te_me <- te_me[te_me$Log10PValue >= -log10(0.05) & te_me$fold.change >= 2 & te_me$samples >= 5,]
plotPCE(te_me, "TE ME gd19.5")
```